global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node:9100"]

#remote_write:
#  - url: "/test"
#    basic_auth:
#      username: "admin"
#      password: "test"
